### PR TITLE
fix: add collapsible and chat to itemstatus

### LINKED ISSUE #309: Add collapsible status badge

### PR DESCRIPTION
**Pull request by spaenleh**
This PR adds the `isCollapsible` and `showCahtbox` statuses to the item badges.
Capture d’écran 2023-03-30 à 12 01 51

closes #309

### CODE REVIEW

File: src/ItemBadges/ItemBadges.tsx [hunk 1]
```diff
@@ -44,10 +52,14 @@ const ItemBadges = ({
...
   isPublicTooltip = 'Public',
+  isCollapsible = false,
+  isCollapsibleTooltip = 'Collapsible',
+  showChatbox = false,
+  showChatboxTooltip = 'Chat',
   backgroundColor = 'grey.600',
 }: Props): JSX.Element => {
   return (
-    <AvatarGroup>
+    <AvatarGroup max={10}>
```
Comment (dialexo) [inline src/ItemBadges/ItemBadges.tsx:62]: Info: do we use this `max` prop as a "safety" to display properly?

File: src/ItemBadges/ItemBadges.tsx [hunk 2]
```diff
@@ -44,10 +52,14 @@ const ItemBadges = ({
   isPublishedTooltip = 'Published',
   isPublic = false,
   isPublicTooltip = 'Public',
+  isCollapsible = false,
+  isCollapsibleTooltip = 'Collapsible',
+  showChatbox = false,
+  showChatboxTooltip = 'Chat',
```
Comment (dialexo) [inline src/ItemBadges/ItemBadges.tsx:58]: Should the tooltips get their values from translations?

**Review by dialexo — APPROVED** [review]
Thank you 🐱 I have some questions but LGTM

File: src/ItemBadges/ItemBadges.tsx (hunk 1 above)
Comment (spaenleh) [reply src/ItemBadges/ItemBadges.tsx:62]: Yes I set it to an arbitrary number higher than the number of badges we use, the default in MUI is `5` after which the avatars are grouped and displayed as (+X)

File: src/ItemBadges/ItemBadges.tsx (hunk 2 above)
Comment (spaenleh) [reply src/ItemBadges/ItemBadges.tsx:58]: Yes the consumers of this component should set the tooltips with translated content. The default values are here in case this is used without translations. Maybe I should make the tooltip texts mandatory and not provide default values ?

Comment (dialexo) [reply src/ItemBadges/ItemBadges.tsx:58]: I think it's fine for now, but yes IMO the boundaries are not well-defined. The consumers still have to each redo the work for the translations in this instance, even though the semantics that are tied to the item models are enclosed from within the component.
