### PR TITLE
fix: use MimeTypes and ThumbnailSize from sdk

### LINKED ISSUE #273: Use ThumbnailSize from sdk

### PR DESCRIPTION
**Pull request by spaenleh**
This PR uses sdk verion `0.8.0` and updates the usage of `MIME_TYPES` and `ThumbnailSize` to the ones provided by sdk.

closes #273

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -1,8 +1,13 @@
+import { ThumbnailSize } from '@graasp/sdk/frontend';
+
 export const DRAWER_WIDTH = 240;
 export const DEFAULT_DIRECTION = 'ltr';
 export const DRAWER_HEADER_HEIGHT = 55;
 export const LOADING_TEXT = '…';
 
+/**
```
Comment (dialexo) [inline src/constants.ts:8]: Q: why can't we just remove this?

File: src/icons/ItemIcon.tsx [hunk 2]
```diff
@@ -93,23 +94,23 @@ const ItemIcon: FC<ItemIconProps> = ({
     case ItemType.LOCAL_FILE:
     case ItemType.S3_FILE: {
       if (mimetype) {
-        if (MIME_TYPES.IMAGE.includes(mimetype)) {
+        if (MIME_TYPES.isImage(mimetype)) {
```
Comment (dialexo) [inline src/icons/ItemIcon.tsx:97]: Nitpick: not sure if it makes sense that `MIME_TYPES` is uppercase, it seems particularly striking here on a method call. I see it more as a static object, so I would probably write it as `MimeTypes`. Should this be changed in SDK?

**Review by dialexo — APPROVED** [review]
LGTM 🏖️ I've left 2 small nitpicks

File: src/icons/ItemIcon.tsx (hunk 2 above)
Comment (spaenleh) [reply src/icons/ItemIcon.tsx:97]: Yes we can change the naming in sdk.
