### PR TITLE
fix: update analytics url for platform switch

### LINKED ISSUE #481: Update analytics url in PlatformSwitch's hook

### PR DESCRIPTION
**Pull request by pyphilia**
close #481

### CODE REVIEW

File: src/PlatformSwitch/hooks.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export type HostsMapper = Partial<
  *  BUILDER_HOST/items/<itemId>
  *  PLAYER_HOST/<itemId>
  *  LIBRARY_HOST/<itemId>
+ *  ANALYTICS/items/<itemId>
```
Comment (spaenleh) [inline src/PlatformSwitch/hooks.ts:22]:
```suggestion
 *  ANALYTICS_HOST/items/<itemId>
```

**Review by spaenleh — APPROVED** [review]
Looks good, just minor comment 📖
