### PR TITLE
fix: set default skeleton variant to circular for Avatar

### LINKED ISSUE #263: Set default for skeleton variant in Avatar

### PR DESCRIPTION
**Pull request by spaenleh**
This PR updates the default skeleton shape value for the `Avatar` component.

closes #263

### CODE REVIEW

File: src/items/ItemSkeleton/ItemSkeleton.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ export interface ItemSkeletonProps {
    */
   isChildren: boolean;
   isCollapsible?: boolean;
-  itemType: ItemType;
+  itemType: `${ItemType}` | ItemType;
```
Comment (dialexo) [inline src/items/ItemSkeleton/ItemSkeleton.tsx:19]: Cool 😎

File: src/items/ItemSkeleton/ItemSkeleton.tsx [hunk 2]
```diff
@@ -48,12 +48,14 @@ const ItemSkeleton: React.FC<ItemSkeletonProps> = ({
...
-      ItemType.APP,
-    ].includes(itemType): {
+    case (
+      [
+        ItemType.LOCAL_FILE,
+        ItemType.S3_FILE,
+        ItemType.LINK,
+        ItemType.APP,
+      ] as string[]
+    ).includes(itemType): {
```
Comment (dialexo) [inline src/items/ItemSkeleton/ItemSkeleton.tsx:58]: Why is this typing necessary?

**Review by dialexo — APPROVED** [review]

File: src/items/ItemSkeleton/ItemSkeleton.tsx (hunk 2 above)
Comment (spaenleh) [reply src/items/ItemSkeleton/ItemSkeleton.tsx:58]: Without it, the type of the array is `ItemType[]` and the values of the union type can't be compared because the types do not match.
Capture d’écran 2023-03-02 à 15 05 42

Comment (spaenleh) [reply src/items/ItemSkeleton/ItemSkeleton.tsx:58]: Maybe we can do:
```ts
[
        ItemType.LOCAL_FILE,
        ItemType.S3_FILE,
        ItemType.LINK,
        ItemType.APP,
      ] as `${ItemType}`[]
    ).includes(itemType):
```
