### PR TITLE
Show Iframe Link

### LINKED ISSUE #16: Show link for iframe
When viewing a link, this can display a embedded object (ie, youtube video) or an iframe. Sometimes it can fail so a link aside might be needed to actually get access to this item.

### PR DESCRIPTION
**Pull request by abdallah75**
close #16

### CODE REVIEW

File: src/items/LinkItem.js [hunk 1]
```diff
@@ -1,13 +1,31 @@
...
+    backgroundColor: 'rgba(62,62,62,0.55)',
+  },
+  linkButton: {
+    padding: 2,
+    marginLeft: 'auto',
+    marginRight: 'auto',
+  },
+  linkButtonIcon: {
+    color: 'white',
+    fontSize: 46,
```
Comment (pyphilia) [inline src/items/LinkItem.js:27]: Let's factor out width, height, color and fontsize in constants.

File: src/items/LinkItem.js [hunk 2]
```diff
@@ -20,6 +38,8 @@ const LinkItem = ({
 }) => {
   const classes = useStyles();
 
+  const [loaded, setLoaded] = useState(false);
```
Comment (pyphilia) [inline src/items/LinkItem.js:41]: Usually boolean starts with `is` or `has` maybe `isLoading` would be a better boolean name (and default to `true`)

File: src/items/LinkItem.js [hunk 3]
```diff
@@ -47,14 +67,40 @@ const LinkItem = ({
...
+      <div
+        hidden={loaded}
+        style={{ position: 'relative', height: height || '100%' }}
+      >
+        Link is Loading.
+        <a href={url}> Click here to open link manually.</a>
+      </div>
+      <div
+        hidden={!loaded}
+        style={{ position: 'relative', height: height || '100%' }}
```
Comment (pyphilia) [inline src/items/LinkItem.js:85]: Factor out styles in `useStyles`.

**Review by pyphilia — CHANGES_REQUESTED** [review]
Nice! I left some minor comments.

File: src/items/LinkItem.js [hunk 4]
```diff
@@ -47,14 +77,42 @@ const LinkItem = ({
...
-      src={url}
-      height={height}
-    />
+    <React.Fragment>
+      <div
+        hidden={!isLoading}
+        className={classes.iframeContainer}
+        style={{ height: height || '100%' }}
+      >
+        Link is Loading.
```
Comment (pyphilia) [inline src/items/LinkItem.js:91]: Provide a prop to define a custom message. In our case it will allow us to provide some translation.

File: src/items/LinkItem.js [hunk 5]
```diff
@@ -1,13 +1,41 @@
...
+  linkButtonContainer: {
+    position: 'absolute',
+    bottom: 0,
+    right: 0,
+    width: LINK_BUTTON_CONTAINER_WIDTH,
+    height: LINK_BUTTON_CONTAINER_HEIGHT,
+    backgroundColor: LINK_BUTTON_CONTAINER_BACKGROUND_COLOR,
+  },
+  linkButton: {
+    padding: 2,
```
Comment (pyphilia) [inline src/items/LinkItem.js:28]: Use `theme.spacing`.

File: src/items/LinkItem.js [hunk 6]
```diff
@@ -47,14 +77,42 @@ const LinkItem = ({
...
-      height={height}
-    />
+    <React.Fragment>
+      <div
+        hidden={!isLoading}
+        className={classes.iframeContainer}
+        style={{ height: height || '100%' }}
+      >
+        Link is Loading.
+        <a href={url}> Click here to open link manually.</a>
```
Comment (pyphilia) [inline src/items/LinkItem.js:92]: Same as above.

**Review by pyphilia — CHANGES_REQUESTED** [review]
Nice! We can merge after these requested changes.
