### PR TITLE
fix: use precise item type in DocumentItem given showCollapse

### LINKED ISSUE #341: Update type of `DocumentItem`
See https://github.com/graasp/graasp-builder/issues/614

The props must be changed to accept a discriminated union of `& ({showCollapse: true, item: { name: string, extra: DocumentItemExtra }} | {showCollapse: false, item: { extra: DocumentItemExtra }})`

Currently, the collapsible property is implemented by each item display (because some items may display differently if they are in a collapsible state, such as iframes). In the future, consider moving to a more decoupled API:

```tsx
<Collapsible>
   <FooItem />
</Collapsible>
```

if `FooItem` requires some changes because of `Collapsible`, use a context and provide a hook instead. This makes it possible to add Collapsible to anything, and only specify additional implementation when needed (instead of forcing the API to change at each item level).

```tsx
// Collapsible.tsx
const useIsCollapsible = () => useContext(collapsibleContext)
const Collapsible = () => {
    return <Context.Provider value={collapsibleContext} />
      //... implementation of collapsible
      {children}
    </Context.Provider>
}

// FooItem.tsx
const FooItem = () => {
  const collapsibleState = useIsCollapsible()
  return <>{ /* implementation that depends on collapsibleState */}</>
}
```

### PR DESCRIPTION
**Pull request by dialexo**
Closes #341

### CODE REVIEW

File: src/items/DocumentItem.tsx [hunk 1]
```diff
@@ -24,9 +23,11 @@ export interface DocumentItemProps {
   saveButtonText?: string;
   showActions?: boolean;
   showEmpty?: boolean;
-  showCollapse?: boolean;
   styles?: React.CSSProperties;
-}
+} & (
+  | { showCollapse: true; item: DocumentItemTypeRecord }
+  | { showCollapse?: false; item: Pick<DocumentItemType, 'extra'> }
```
Comment (spaenleh) [inline src/items/DocumentItem.tsx:29]: I am curious whether it works if you don't have exactly the same type, since you are marking `showCollapse` as optional.

**Review by spaenleh — APPROVED** [review]
✅ This looks good to me if it works in the builder 🔨  !

File: src/items/DocumentItem.tsx (hunk 1 above)
Comment (dialexo) [reply src/items/DocumentItem.tsx:29]: Yes, for the compiler this is the same as `showCollapse: true | false | undefined`. So `undefined` is handled by the second type.

File: src/items/DocumentItem.tsx [hunk 2]
```diff
@@ -44,7 +45,7 @@ const DocumentItem: FC<DocumentItemProps> = ({
   saveButtonText,
   showActions,
   showEmpty,
-  showCollapse = false,
+  showCollapse,
```
[the remark this answers is not in the document]
Comment (dialexo) [reply src/items/DocumentItem.tsx:48]: Not sure, in any case since we handle it with `if(showCollapse)` both `false` and `undefined` are captured
